[build]
  command = "npx next build"
  publish = "out"

[build.environment]
  RUSTUP_HOME = "/opt/buildhome/.rustup"
  CARGO_HOME = "/opt/buildhome/.cargo"
  PATH = "/opt/buildhome/.cargo/bin:$PATH"

[[plugins]]
  package = "@netlify/plugin-rustup"
